export const {
    NODE_ENV,
    SPOTIFY_REFRESH_TOKEN,
    SPOTIFY_CLIENT_SECRET,
    SPOTIFY_CLIENT_ID,
    WAKATIME_API_KEY,
    WAKATIME_USER,
    EMAIL_SENDER,
    EMAIL_RECEIVER,
    PUBLIC_APP_GITHUB_ACCESS_TOKEN,
    RESEND_API_KEY,
} = process.env;
